version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: %NAME%_sonarr
    environment:
      - PUID=2001
      - PGID=2001
      - TZ=Europe/Paris
    volumes:
      - /media/test/sonarr/config:/config
      - /media/test/seedbox/media/Series:/tv
      - /media/test/seedbox/downloads:/downloads
    ports:
      - 8999:8989
    restart: unless-stopped
