version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: %NAME%_sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /media/test/sonarr/config:/config
      - /media/test/seedbox/media/Series:/tv
      - /media/test/seedbox/downloads:/downloads
    ports:
      - 8999:8989
    restart: unless-stopped
